server:
  port: 80

tmp:
  temporary

s3prefix:
  website-resource/modify

s3bucket:
  zhonghaollc



#spring:

##showSql
#logging:
#  level:
#    com:
#      example:
#        mapper : debug