server:
  port: 80

spring:
  datasource:
    username: jingting
    password: pa$$w0rd
    url: jdbc:mysql://zhonghaollc-db.c1xl8hxe4v20.us-east-2.rds.amazonaws.com:3306/zhonghaollc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhonghaollc.zhonghaosite.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug